SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO

/******************* Catálogo de Localidades SAT ***********/
TRUNCATE TABLE SATLocalidad
GO
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','AGU','Aguascalientes'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','AGU','Asientos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','AGU','Calvillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','AGU','Cosío'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','AGU','Jesús María'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','AGU','Pabellón de Arteaga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','AGU','Rincón de Romos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','AGU','San Francisco de los Romo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','AGU','Tepezalá'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','BCN','Ensenada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','BCN','Mexicali'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','BCN','Tecate'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','BCN','Tijuana'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','BCN','Playas de Rosarito'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','BCN','Rodolfo Sánchez T. (Maneadero)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','BCN','San Felipe'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','BCS','Ciudad Constitución'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','BCS','La Paz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','BCS','Cabo San Lucas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','BCS','San José del Cabo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','BCS','Loreto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','BCS','Puerto Adolfo López Mateos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','BCS','Todos Santos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','BCS','Heroica Mulegé'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','BCS','Villa Alberto Andrés Alvarado Arámburo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','BCS','San Ignacio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','BCS','Guerrero Negro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','CAM','San Francisco de Campeche'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','CAM','Ciudad del Carmen'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','CAM','Calkini'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','CAM','Candelaria'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','CAM','Escárcega'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','CAM','Sabancuy'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','CAM','Hopelchén'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','CAM','Champotón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','CAM','Hecelchakán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','CAM','Pomuch'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','CHH','Santa Rosalía de Camargo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','CHH','Chihuahua'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','CHH','Cuauhtémoc'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','CHH','Delicias'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','CHH','Hidalgo del Parral'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','CHH','Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','CHH','Nuevo Casas Grandes'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','CHH','Madera'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','CHH','Colonia Anáhuac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','CHH','Juan Aldama'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','CHH','José Mariano Jiménez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','CHH','Manuel Ojinaga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','CHH','Bachíniva'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','CHH','Saucillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','CHP','Comitán de Domínguez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','CHP','San Cristóbal de las Casas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','CHP','Tapachula de Córdova y Ordóñez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','CHP','Tuxtla Gutiérrez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','CHP','Venustiano Carranza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','CHP','Jiquipilas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','CHP','Villaflores'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','CHP','Las Margaritas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','CHP','Arriaga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','CHP','Palenque'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','CHP','Ocosingo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','CHP','Tonalá'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','CHP','Mapastepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','CHP','Las Rosas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','CHP','Chiapa de Corzo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','CHP','Cacahoatán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','CHP','Ocozocoautla de Espinosa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','CHP','Cintalapa de Figueroa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','CHP','Pichucalco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','CHP','Puerto Madero (San Benito)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','CHP','Pijijiapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','CHP','Reforma'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','CHP','Huixtla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','CHP','Motozintla de Mendoza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','CHP','Acala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','COA','Ciudad Acuña'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','COA','Frontera'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','COA','Matamoros'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','COA','Monclova'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','COA','Parras de la Fuente'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','COA','Piedras Negras'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','COA','Sabinas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','COA','Saltillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','COA','Nueva Rosita'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','COA','San Pedro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','COA','Torreón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','COA','Castaños'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','COA','Francisco I. Madero (Chávez)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','COA','Cuatro Ciénegas de Carranza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','COA','Nadadores'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','COA','Ramos Arizpe'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','COA','Nava'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','COA','Zaragoza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','COA','San Buenaventura'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','COA','Ciudad Melchor Múzquiz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','COA','Viesca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','COA','Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','COA','Arteaga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','COA','Allende'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','COL','Colima'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','COL','Manzanillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','COL','Tecoman'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','COL','Ciudad de Villa de Álvarez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','COL','Ciudad de Armería'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','DIF','Ciudad de México'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','DUR','Victoria de Durango'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','DUR','Gómez Palacio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','DUR','Ciudad Lerdo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','DUR','Santiago Papasquiaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','DUR','Canatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','DUR','San Juan del Río del Centauro del Norte'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','DUR','Peñón Blanco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','DUR','Francisco I. Madero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','DUR','Nombre de Dios'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','DUR','Vicente Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','DUR','El Salto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','DUR','Santa María del Oro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','GRO','Acapulco de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','GRO','Chilpancingo de los Bravo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','GRO','Iguala de la Independencia'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','GRO','Taxco de Alarcón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','GRO','Arcelia'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','GRO','Ayutla de los Libres'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','GRO','Atoyac de Álvarez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','GRO','San Jerónimo de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','GRO','Ciudad Apaxtla de Castrejón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','GRO','Ciudad Altamirano'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','GRO','Buenavista de Cuellar'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','GRO','Cutzamala de Pinzón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','GRO','Coyuca de Catalán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','GRO','Tierra Colorada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','GRO','Coyuca de Benítez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','GRO','Olinalá'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','GRO','Marquelia'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','GRO','Zumpango del Río'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','GRO','San Luis de la Loma'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','GRO','Petatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','GRO','La Unión'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','GRO','San Luis San Pedro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','GRO','Teloloapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','GRO','Técpan de Galeana'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','GRO','Huitzuco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','GRO','Tixtla de Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','GRO','Tepecoacuilco de Trujano'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','GRO','San Marcos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','GRO','Azoyú'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','GRO','Tlapehuala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','GRO','San Luis Acatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '33','GRO','Chilapa de Álvarez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '34','GRO','Tlapa de Comonfort'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '35','GRO','Tlalixtaquilla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','GRO','Cuajinicuilapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '37','GRO','Huamuxtitlan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '38','GRO','Cruz Grande'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','GRO','Ocotito'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '40','GRO','Copala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '41','GRO','Zihuatanejo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','GUA','Acámbaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','GUA','San miguel de Allende'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','GUA','Celaya'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','GUA','Cortazar'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','GUA','Guanajuato'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','GUA','Irapuato'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','GUA','León de los Aldama'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','GUA','Moroleón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','GUA','Salamanca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','GUA','San Francisco del Rincón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','GUA','Silao'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','GUA','Jerécuaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','GUA','Santiago Maravatío'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','GUA','Romita'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','GUA','Tarandacuao'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','GUA','Huanímaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','GUA','Comonfort'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','GUA','Uriangato'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','GUA','Pénjamo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','GUA','Cuerámaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','GUA','Empalme Escobedo (Escobedo)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','GUA','San Luis de la Paz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','GUA','Valle de Santiago'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','GUA','Abasolo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','GUA','Rincón de Tamayo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','GUA','Villagrán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','GUA','Yuriria'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','GUA','Apaseo el Grande'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','GUA','Purísima de Bustos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','GUA','Salvatierra'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','GUA','Marfil'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','GUA','San José Iturbide'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '33','GUA','Apaseo el Alto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '34','GUA','Ciudad Manuel Doblado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '35','GUA','Jaral del Progreso'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','GUA','San Diego de la Unión'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '37','GUA','Santa Cruz Juventino Rosas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '38','GUA','Doctor Mora'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','GUA','Dolores Hidalgo Cuna de la Independencia Nacional'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','HID','Actopan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','HID','Apan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','HID','Pachuca de Soto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','HID','Ciudad de Fray Bernardino de Sahagún'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','HID','Tula de Allende'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','HID','Tulancingo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','HID','Zimapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','HID','Huejutla de Reyes'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','HID','Tlaxcoapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','HID','Tizayuca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','HID','Santiago Tulantepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','HID','Ixmiquilpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','HID','Tepeji del Rio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','HID','Cruz Azul'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','HID','Tepeapulco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','JAL','Ameca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','JAL','Ciudad Guzmán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','JAL','Guadalajara'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','JAL','Lagos de Moreno'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','JAL','Ocotlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','JAL','Puerto Vallarta'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','JAL','San Juan de los Lagos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','JAL','Tepatitlán de Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','JAL','Tlaquepaque'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','JAL','Zapopan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','JAL','Tlajomulco de Zúñiga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','JAL','Tonalá'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','JAL','Tuxpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','JAL','Tototlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','JAL','San Diego de Alejandría'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','JAL','La Resolana'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','JAL','Atotonilco el Alto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','JAL','Jalostotitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','JAL','Poncitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','JAL','Arandas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','JAL','Talpa de Allende'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','JAL','Etzatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','JAL','Sayula'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','JAL','Ahualulco de Mercado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','JAL','Autlán de Navarro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','JAL','Magdalena'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','JAL','San Julián'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','JAL','Cocula'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','JAL','El Grullo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','JAL','San Miguel el Alto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','JAL','Tala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','JAL','La Barca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '33','JAL','Jamay'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '34','JAL','Yahualica de González Gallo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '35','JAL','Colotlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','JAL','Cihuatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '37','JAL','Zapotiltic'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '38','JAL','Villa Corona'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','JAL','Teocaltiche'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '41','JAL','Tequila'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '42','JAL','El Quince (San José el Quince)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '43','JAL','San José el Verde (El Verde)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '44','JAL','Jocotepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '45','JAL','Tecalitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '46','JAL','Chapala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '47','JAL','Ajijic'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '48','JAL','San Ignacio Cerro Gordo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '49','JAL','Zacoalco de Torres'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '50','JAL','Huejuquilla el Alto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '51','JAL','Villa Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '52','JAL','Unión de San Antonio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '53','JAL','Las Pintitas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '54','JAL','Tamazula de Gordiano'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '55','JAL','Acatlán de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '56','JAL','Valle de Guadalupe'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','MEX','Ciudad Adolfo López Mateos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','MEX','Chimalhuacán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','MEX','Coacalco de Berriozabal'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','MEX','Cuautitlán Izcalli'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','MEX','Ecatepec de Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','MEX','Huixquilucan de Degollado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','MEX','Los Reyes Acaquilpan (La Paz)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','MEX','Metepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','MEX','Naucalpan de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','MEX','Ciudad Nezahualcoyotl'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','MEX','Villa Nicolás Romero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','MEX','Tecamac de Felipe Villanueva'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','MEX','Tepotzotlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','MEX','Tlalnepantla de Baz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','MEX','Santa Maria Tultepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','MEX','Tultitlán de Mariano Escobedo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','MEX','Cuautitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','MEX','Ixtapaluca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','MEX','Texcoco de Mora'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','MEX','Toluca de Lerdo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','MEX','Valle de Chalco Solidaridad'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','MEX','Tejupilco de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','MEX','Chalco de Díaz Covarrubias'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','MEX','Amatepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','MEX','Melchor Ocampo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','MEX','San Vicente Chicoloapan de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','MEX','Capulhuac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','MEX','Juchitepec de Mariano Riva Palacio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','MEX','Tequixquiac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','MEX','Xonacatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','MEX','San Mateo Atenco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','MEX','Chiconcuac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','MEX','Almoloya de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '40','MEX','Ocoyoacac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '41','MEX','Zumpango'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','MIC','Apatzingán de la Constitución'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','MIC','Los Reyes de Salgado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','MIC','Ciudad Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','MIC','Jacona de Plancarte'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','MIC','La piedad de Cabadas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','MIC','Morelia'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','MIC','Pátzcuaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','MIC','Sahuayo de Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','MIC','Uruapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','MIC','Zacapu'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','MIC','Zamora de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','MIC','Heroica Zitácuaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','MIC','Paracho de Verduzco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','MIC','Tangancícuaro de Arista'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','MIC','Maravatío de Ocampo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','MIC','Zinapécuaro de Figueroa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','MIC','Puruándiro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','MIC','Yurécuaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','MIC','Huetamo de Núñez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','MIC','Tacámbaro de Codallos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','MIC','Ciudad Lázaro Cárdenas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','MIC','Las Guacamayas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','MIC','Jiquilpan de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','MIC','Tuxpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','MIC','Cotija de la Paz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','MIC','Nueva Italia de Ruiz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','MIC','Cuitzeo del Porvenir'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','MOR','Cuautla (Cuautla de Morelos)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','MOR','Cuernavaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','MOR','Galeana'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','MOR','Jojutla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','MOR','Puente de Ixtla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','MOR','Santa Rosa Treinta'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','MOR','Zacatepec de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','MOR','Tlaquiltenango'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','NAY','Santiago Ixcuintla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','NAY','Tepic'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','NAY','Tuxpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','NAY','Acaponeta'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','NAY','Tecuala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','NAY','Compostela'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','NAY','Francisco I. Madero (Puga)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','NAY','Villa Hidalgo (El Nuevo)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','NAY','Ruiz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','NAY','San Blas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','NAY','Ixtlán del Río'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','NAY','Bucerías'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','NAY','Las Varas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','NAY','Xalisco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','NAY','San pedro Lagunillas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','NAY','La peñita de Jaltemba'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','NAY','Jala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','NAY','Ahuacatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','NLE','Ciudad Apodaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','NLE','San Pedro Garza García'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','NLE','Ciudad General Escobedo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','NLE','Guadalupe'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','NLE','Linares'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','NLE','Montemorelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','NLE','Monterrey'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','NLE','Ciudad Sabinas Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','NLE','San Nicolás de los Garza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','NLE','Ciudad Santa Catarina'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','NLE','Doctor Arroyo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','NLE','Ciénega de Flores'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','NLE','Hualahuises'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','NLE','Cadereyta Jiménez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','NLE','Santiago'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','NLE','El cercado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','NLE','Anáhuac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','NLE','García'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','NLE','Ciudad Benito Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','OAX','Juchitán (Juchitán de Zaragoza)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','OAX','Oaxaca de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','OAX','Salina Cruz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','OAX','San Juan Bautista Tuxtepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','OAX','Matías Romero Avendaño'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','OAX','Heroica Ciudad de Huajuapan de León'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','OAX','Loma Bonita'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','OAX','Puerto Escondido'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','OAX','Río Grande o Piedra Parada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','OAX','Santiago Suchilquitongo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','OAX','San Felipe Jalapa de Díaz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','OAX','Bahias de Huatulco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','OAX','Putla Villa de Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','OAX','Cosolapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','OAX','Tlacolula de Matamoros'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','OAX','San Pablo Villa de Mitla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','OAX','Natividad'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','OAX','Teotitlán de Flores Magón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','OAX','Santa María Huatulco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','OAX','San Juan Bautista Cuicatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','OAX','Villa Sola de Vega'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','OAX','Ocotlán de Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','OAX','Villa de Zaachila'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','OAX','Miahuatlán de Porfirio Díaz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','OAX','Unión Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','OAX','El Camarón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','OAX','San Pedro Mixtepec -Dto. 22-'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','OAX','Santa Cruz Itundujia'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','OAX','Chahuites'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','OAX','Heroica Ciudad de Ejutla de Crespo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','OAX','San Pedro Tapanatepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '33','OAX','Vicente Camalote'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '34','OAX','Villa de Tamazulápam del Progreso'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '35','OAX','San Juan Bautista lo de Soto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','OAX','San Juan Cacahuatepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '37','OAX','San Pedro Totolapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '38','OAX','San Miguel el Grande'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','OAX','Zimatlán de Álvarez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '40','OAX','San Pablo Huitzo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '41','OAX','San Francisco Telixtlahuaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '42','OAX','Mariscala de Juárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '43','OAX','Santiago Pinotepa Nacional'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '44','OAX','Santiago Jamiltepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '45','OAX','San Pedro Pochutla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '46','OAX','Heroica Ciudad de Tlaxiaco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '47','OAX','San Juan Bautista Valle Nacional'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '48','OAX','Lagunas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '49','OAX','Ciudad Ixtepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '50','OAX','Santiago Juxtlahuaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '51','OAX','San Sebastián Tecomaxtlahuaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '52','OAX','Asunción Nochixtlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '53','OAX','San Francisco Ixhuatán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '54','OAX','San Blas Atempa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '55','OAX','Santo Domingo Tehuantepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '56','OAX','Cuilápam de Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '57','OAX','El Rosario'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '58','OAX','Santa Lucia del Camino'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '59','OAX','San Antonio de la Cal'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','PUE','Atlixco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','PUE','Izúcar de Matamoros'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','PUE','Puebla (Heroica Puebla)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','PUE','San Martín Texmelucan de Labastida'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','PUE','Tehuacan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','PUE','Teziutlan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','PUE','San Andrés Cholula'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','PUE','San Pedro Cholula'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','PUE','Huauchinango'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','PUE','Acatlán de Osorio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','PUE','Cuautlancingo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','PUE','Tepeaca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','PUE','Tecamachalco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','PUE','Zacatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','PUE','Xicotepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','PUE','Ciudad Serdán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','PUE','Amozoc'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','QUE','Querétaro'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','QUE','San Juan del Rio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','QUE','El Pueblito'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','ROO','Cancún'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','ROO','Cozumel'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','ROO','Felipe Carrillo Puerto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','ROO','Chetumal'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','ROO','Playa del Carmen'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','ROO','Kantunilkín'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','ROO','Isla Mujeres'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','ROO','Bacalar'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','SIN','Los Mochis'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','SIN','Culiacán Rosales'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','SIN','Escuinapa de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','SIN','Guasave'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','SIN','Mazatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','SIN','Guamúchil'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','SIN','Navolato'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','SIN','Quila'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','SIN','Ahome'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','SIN','Higuera de Zaragoza'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','SIN','Choix'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','SIN','Villa Unión'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','SIN','Sinaloa de Leyva'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','SIN','Mocorito'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','SIN','Angostura'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','SIN','San Blas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','SIN','La Cruz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','SIN','El rosario'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','SIN','Estación Naranjo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','SIN','Aguaruto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','SIN','Cosalá'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','SIN','San Ignacio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','SIN','Topolobampo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','SIN','Lic. Benito Juárez (Campo Gobierno)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','SLP','Ciudad Valles'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','SLP','Ébano'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','SLP','Matehuala'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','SLP','Rioverde'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','SLP','San Luis Potosí'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','SLP','Soledad de Graciano Sánchez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','SLP','Charcas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','SLP','Salinas de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','SLP','Cárdenas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','SLP','Cerritos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','SLP','Tamuin'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','SLP','Tamasopo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','SLP','Ciudad del Maíz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','SLP','Cedral'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','SLP','Tierra Nueva'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','SLP','Villa de Reyes'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','SLP','Fracción el Refugio'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','SLP','Tamazunchale'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','SLP','Santa María del Río'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','SLP','El Naranjo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','SON','San Luis Río Colorado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','SON','Agua Prieta'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','SON','Heroica Caborca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','SON','Ciudad Obregón'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','SON','Empalme'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','SON','Heroica Guaymas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','SON','Hermosillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','SON','Huatabampo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','SON','Navojoa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','SON','Heroica Nogales'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','SON','Puerto Peñasco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','SON','Heroica Ciudad de Cananea'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','SON','Sonoita'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','SON','Magdalena de Kino'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','TAB','Cárdenas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','TAB','Villahermosa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','TAB','Comalcalco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','TAB','Emiliano Zapata'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','TAB','Jalpa de Méndez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','TAB','Macuspana'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','TAB','Tenosique de Pino Suárez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','TAB','Teapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','TAB','Paraíso'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','TAB','Frontera'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','TAB','Cunduacán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','TAB','Huimanguillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','TAM','Altamira'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','TAM','Ciudad Camargo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','TAM','Ciudad Madero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','TAM','Ciudad Mante'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','TAM','Heroica Matamoros'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','TAM','Nuevo Laredo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','TAM','Reynosa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','TAM','Ciudad Río Bravo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','TAM','San Fernando'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','TAM','Tampico'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','TAM','Ciudad Victoria'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','TAM','González'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','TAM','Jaumave'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','TAM','Ciudad Gustavo Díaz Ordaz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','TAM','Estación Manuel (Úrsulo Galván)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','TAM','Xicoténcatl'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','TAM','Ciudad Miguel Alemán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','TAM','Soto la Marina'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','TAM','Ciudad Tula'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','TAM','Nueva Ciudad Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','TAM','Valle Hermoso'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','TLA','Apizaco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','TLA','Villa Vicente Guerrero'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','TLA','Tlaxcala (Tlaxcala de Xicotencatl)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','TLA','Huamantla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','TLA','Calpulalpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','TLA','Chiautempan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','VER','Acayucan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','VER','Naranjos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','VER','Boca del RÍo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','VER','Coatepec'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','VER','Agua dulce'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','VER','Coatzacoalcos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','VER','Córdoba'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','VER','Tres Valles'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','VER','Jáltipan de Morelos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','VER','Xalapa-Enríquez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','VER','Minatitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','VER','Orizaba'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','VER','Papantla de Olarte'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','VER','Poza Rica de Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','VER','San Andrés Tuxtla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','VER','Túxpam de Rodríguez Cano'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','VER','Veracruz'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','VER','Tierra Blanca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','VER','Cosamaloapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '20','VER','Carlos A. Carrillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '21','VER','Pánuco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '22','VER','Tampico Alto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '23','VER','Tempoal de Sánchez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '24','VER','Tantoyuca'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '25','VER','Gutiérrez Zamora'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '26','VER','Platón Sánchez'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '27','VER','Juan Rodríguez Clara'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '28','VER','Huatusco de Chicuellar'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '29','VER','Ixtaczoquitlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '30','VER','Río Blanco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '31','VER','Isla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '32','VER','Cuitláhuac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '33','VER','Fortín de las Flores'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '34','VER','Alvarado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '35','VER','José Cardel'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '36','VER','Banderilla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '37','VER','Paraje Nuevo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '38','VER','Playa Vicente'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '39','VER','Altotonga'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '40','VER','Juan Díaz Covarrubias'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '41','VER','Cuichapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '42','VER','Santiago Tuxtla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '43','VER','Huayacocotla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '44','VER','Paso de Ovejas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '45','VER','Catemaco'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '46','VER','Nogales'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '47','VER','Las Choapas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '48','VER','General Miguel Alemán (Potrero Nuevo)'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '49','VER','Coatzintla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '50','VER','Ángel R. Cabada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '51','VER','San Rafael'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '52','VER','Tlacojalpan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '53','VER','Cosoleacaque'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '54','VER','Lerdo de Tejada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '55','VER','Tihuatlán'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '56','VER','Atoyac'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '57','VER','Huiloapan de Cuauhtémoc'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '58','VER','Cazones de Herrera'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '59','VER','Yecuatla'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '60','VER','Soledad de Doblado'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '61','VER','Cerro Azul'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '62','VER','Tezonapa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '66','VER','Sihuapan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '67','VER','El Higo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '68','VER','Paso del Macho'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '69','VER','Tlapacoyan'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','YUC','Mérida'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','YUC','Tizimín'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','YUC','Ticul'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','YUC','Motul de Carrillo Puerto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','YUC','Valladolid'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','YUC','Kanasín'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '01','ZAC','Fresnillo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '02','ZAC','Jerez de García Salinas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '03','ZAC','Zacatecas'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '04','ZAC','Guadalupe'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '05','ZAC','Río Grande'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '06','ZAC','Ciudad Cuauhtémoc'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '07','ZAC','Ojocaliente'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '08','ZAC','Villa Hidalgo'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '09','ZAC','Villanueva'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '10','ZAC','Villa de Cos'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '11','ZAC','Nochistlán de Mejía'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '12','ZAC','Víctor Rosales'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '13','ZAC','Valparaíso'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '14','ZAC','Luis Moya'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '15','ZAC','Moyahua de Estrada'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '16','ZAC','Sombrerete'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '17','ZAC','Jalpa'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '18','ZAC','Loreto'
INSERT INTO SATLocalidad(ClaveLocalidad, ClaveEstado, Descripcion)  SELECT '19','ZAC','Juan Aldama'
GO