SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO

/******************* Catálogo de Países SAT ***********/
TRUNCATE TABLE SATPais
GO
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ABW','Aruba','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AFG','Afganistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AGO','Angola','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AIA','Anguila','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ALA','Islas Åland','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ALB','Albania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AND','Andorra','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ARE','Emiratos Árabes Unidos (Los)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ARG','Argentina','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ARM','Armenia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ASM','Samoa Americana','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ATA','Antártida','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ATF','Territorios Australes Francese','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ATG','Antigua y Barbuda','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AUS','Australia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AUT','Austria','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'AZE','Azerbaiyán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BDI','Burundi','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BEL','Bélgica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BEN','Benín','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BES','Bonaire, San Eustaquio y Saba','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BFA','Burkina Faso','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BGD','Bangladés','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BGR','Bulgaria','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BHR','Baréin','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BHS','Bahamas (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BIH','Bosnia y Herzegovina','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BLM','San Bartolomé','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BLR','Bielorrusia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BLZ','Belice','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BMU','Bermudas','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BOL','Bolivia, Estado Plurinacional','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BRA','Brasil','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BRB','Barbados','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BRN','Brunéi Darussalam','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BTN','Bután','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BVT','Isla Bouvet','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'BWA','Botsuana','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CAF','República Centroafricana (la)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CAN','Canadá','[A-Z][0-9][A-Z] [0-9][A-Z][0-9]','[0-9]{9}',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CCK','Islas Cocos (Keeling)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CHE','Suiza','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CHL','Chile','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CHN','China','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CIV','Côte d''''Ivoire','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CMR','Camerún','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'COD','Congo (República Democrática)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'COG','Congo','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'COK','Islas Cook (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'COL','Colombia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'COM','Comoras','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CPV','Cabo Verde','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CRI','Costa Rica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CUB','Cuba','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CUW','Curaçao','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CXR','Isla de Navidad','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CYM','Islas Caimán (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CYP','Chipre','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'CZE','República Checa (la)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DEU','Alemania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DJI','Yibuti','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DMA','Dominica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DNK','Dinamarca','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DOM','República Dominicana (la)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'DZA','Argelia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ECU','Ecuador','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'EGY','Egipto','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ERI','Eritrea','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ESH','Sahara Occidental','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ESP','España','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'EST','Estonia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ETH','Etiopía','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FIN','Finlandia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FJI','Fiyi','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FLK','Islas Malvinas','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FRA','Francia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FRO','Islas Feroe (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'FSM','Micronesia (Estados Federados)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GAB','Gabón','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GBR','Reino Unido (el)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GEO','Georgia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GGY','Guernsey','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GHA','Ghana','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GIB','Gibraltar','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GIN','Guinea','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GLP','Guadalupe','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GMB','Gambia (La)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GNB','Guinea-Bisáu','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GNQ','Guinea Ecuatorial','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GRC','Grecia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GRD','Granada','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GRL','Groenlandia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GTM','Guatemala','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GUF','Guayana Francesa','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GUM','Guam','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'GUY','Guyana','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HKG','Hong Kong','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HMD','Isla Heard e Islas McDonald','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HND','Honduras','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HRV','Croacia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HTI','Haití','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'HUN','Hungría','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IDN','Indonesia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IMN','Isla de Man','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IND','India','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IOT','Territ Británico Océano Índico','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IRL','Irlanda','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IRN','Irán la República Islámica de','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'IRQ','Irak','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ISL','Islandia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ISR','Israel','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ITA','Italia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'JAM','Jamaica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'JEY','Jersey','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'JOR','Jordania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'JPN','Japón','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KAZ','Kazajistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KEN','Kenia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KGZ','Kirguistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KHM','Camboya','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KIR','Kiribati','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KNA','San Cristóbal y Nieves','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KOR','Corea (la República de)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'KWT','Kuwait','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LAO','Lao, República Democrática Pop','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LBN','Líbano','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LBR','Liberia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LBY','Libia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LCA','Santa Lucía','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LIE','Liechtenstein','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LKA','Sri Lanka','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LSO','Lesoto','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LTU','Lituania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LUX','Luxemburgo','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'LVA','Letonia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MAC','Macao','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MAF','San Martín (parte francesa)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MAR','Marruecos','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MCO','Mónaco','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MDA','Moldavia (la República de)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MDG','Madagascar','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MDV','Maldivas','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MEX','México','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MHL','Islas Marshall (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MKD','Macedonia (Rep Yugoslava)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MLI','Malí','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MLT','Malta','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MMR','Myanmar','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MNE','Montenegro','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MNG','Mongolia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MNP','Islas Marianas del Norte','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MOZ','Mozambique','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MRT','Mauritania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MSR','Montserrat','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MTQ','Martinica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MUS','Mauricio','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MWI','Malaui','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MYS','Malasia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'MYT','Mayotte','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NAM','Namibia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NCL','Nueva Caledonia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NER','Níger (el)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NFK','Isla Norfolk','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NGA','Nigeria','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NIC','Nicaragua','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NIU','Niue','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NLD','Países Bajos (los)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NOR','Noruega','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NPL','Nepal','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NRU','Nauru','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'NZL','Nueva Zelanda','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'OMN','Omán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PAK','Pakistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PAN','Panamá','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PCN','Pitcairn','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PER','Perú','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PHL','Filipinas (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PLW','Palaos','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PNG','Papúa Nueva Guinea','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'POL','Polonia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PRI','Puerto Rico','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PRK','Corea (República Democrática)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PRT','Portugal','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PRY','Paraguay','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PSE','Palestina, Estado de','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'PYF','Polinesia Francesa','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'QAT','Catar','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'REU','Reunión','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ROU','Rumania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'RUS','Rusia, (la) Federación de','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'RWA','Ruanda','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SAU','Arabia Saudita','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SDN','Sudán (el)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SEN','Senegal','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SGP','Singapur','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SGS','Georgia del sur y las islas','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SHN','Santa Helena, Ascensión y Tris','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SJM','Svalbard y Jan Mayen','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SLB','Islas Salomón (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SLE','Sierra leona','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SLV','El Salvador','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SMR','San Marino','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SOM','Somalia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SPM','San Pedro y Miquelón','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SRB','Serbia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SSD','Sudán del Sur','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'STP','Santo Tomé y Príncipe','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SUR','Surinam','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SVK','Eslovaquia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SVN','Eslovenia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SWE','Suecia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SWZ','Suazilandia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SXM','Sint Maarten (parte holandesa)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SYC','Seychelles','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'SYR','Siria, (la) República Árabe','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TCA','Islas Turcas y Caicos (las)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TCD','Chad','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TGO','Togo','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'THA','Tailandia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TJK','Tayikistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TKL','Tokelau','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TKM','Turkmenistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TLS','Timor-Leste','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TON','Tonga','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TTO','Trinidad y Tobago','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TUN','Túnez','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TUR','Turquía','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TUV','Tuvalu','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TWN','Taiwán (Provincia de China)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'TZA','Tanzania, República Unida de','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'UGA','Uganda','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'UKR','Ucrania','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'UMI','Islas de Ultramar Menores','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'URY','Uruguay','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'USA','Estados Unidos (los)','[0-9]{5}(-[0-9]{4})?','[0-9]{9}','Archivo publicado por SAT'
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'UZB','Uzbekistán','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VAT','Santa Sede[Ciudad Vaticano]','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VCT','San Vicente y las Granadinas','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VEN','Venezuela, República Boliv','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VGB','Islas Vírgenes (Británicas)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VIR','Islas Vírgenes (EE.UU.)','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VNM','Viet Nam','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'VUT','Vanuatu','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'WLF','Wallis y Futuna','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'WSM','Samoa','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'YEM','Yemen','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ZAF','Sudáfrica','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ZMB','Zambia','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ZWE','Zimbabue','','',''
INSERT INTO SATPais(ClavePais, Descripcion, FormatoCP, FormatoRIT, ValidacionRIT)  SELECT 'ZZZ','Países no declarados','','',''
GO

