SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO

/******************* Catálogo de Estados SAT ***********/
TRUNCATE TABLE SATEstado
GO
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AGU','MEX','Aguascalientes'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'BCN','MEX','Baja California'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'BCS','MEX','Baja California Sur'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CAM','MEX','Campeche'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CHP','MEX','Chiapas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CHH','MEX','Chihuahua'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'COA','MEX','Coahuila'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'COL','MEX','Colima'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'DIF','MEX','Ciudad de México'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'DUR','MEX','Durango'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'GUA','MEX','Guanajuato'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'GRO','MEX','Guerrero'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'HID','MEX','Hidalgo'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'JAL','MEX','Jalisco'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MEX','MEX','Estado de México'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MIC','MEX','Michoacán'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MOR','MEX','Morelos'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NAY','MEX','Nayarit'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NLE','MEX','Nuevo León'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'OAX','MEX','Oaxaca'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'PUE','MEX','Puebla'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'QUE','MEX','Querétaro'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ROO','MEX','Quintana Roo'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SLP','MEX','San Luis Potosí'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SIN','MEX','Sinaloa'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SON','MEX','Sonora'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'TAB','MEX','Tabasco'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'TAM','MEX','Tamaulipas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'TLA','MEX','Tlaxcala'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'VER','MEX','Veracruz'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'YUC','MEX','Yucatán'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ZAC','MEX','Zacatecas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AL','USA','Alabama'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AK','USA','Alaska'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AZ','USA','Arizona'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AR','USA','Arkansas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CA','USA','California'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NC','USA','Carolina del Norte'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SC','USA','Carolina del Sur'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CO','USA','Colorado'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'CT','USA','Connecticut'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ND','USA','Dakota del Norte'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SD','USA','Dakota del Sur'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'DE','USA','Delaware'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'FL','USA','Florida'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'GA','USA','Georgia'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'HI','USA','Hawái'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ID','USA','Idaho'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'IL','USA','Illinois'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'IN','USA','Indiana'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'IA','USA','Iowa'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'KS','USA','Kansas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'KY','USA','Kentucky'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'LA','USA','Luisiana'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ME','USA','Maine'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MD','USA','Maryland'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MA','USA','Massachusetts'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MI','USA','Míchigan'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MN','USA','Minnesota'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MS','USA','Misisipi'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MO','USA','Misuri'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MT','USA','Montana'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NE','USA','Nebraska'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NV','USA','Nevada'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NJ','USA','Nueva Jersey'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NY','USA','Nueva York'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NH','USA','Nuevo Hampshire'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NM','USA','Nuevo México'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'OH','USA','Ohio'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'OK','USA','Oklahoma'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'OR','USA','Oregón'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'PA','USA','Pensilvania'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'RI','USA','Rhode Island'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'TN','USA','Tennessee'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'TX','USA','Texas'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'UT','USA','Utah'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'VT','USA','Vermont'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'VA','USA','Virginia'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'WV','USA','Virginia Occidental'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'WA','USA','Washington'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'WI','USA','Wisconsin'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'WY','USA','Wyoming'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'ON','CAN','Ontario'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'QC','CAN','Quebec'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NS','CAN','Nueva Escocia'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NB','CAN','Nuevo Brunswick'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'MB','CAN','Manitoba'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'BC','CAN','Columbia Británica'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'PE','CAN','Isla del Príncipe Eduardo'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'SK','CAN','Saskatchewan'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'AB','CAN','Alberta'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NL','CAN','Terranova y Labrador'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'NT','CAN','Territorios del Noroeste'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'YT','CAN','Yukón'
INSERT INTO SATEstado(ClaveEstado, ClavePais, Descripcion)  SELECT 'UN','CAN','Nunavut'
GO